import { makeid } from "@/utils/make_id";

export const DEPOSIT = [
  {
    id: 1,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
  {
    id: 2,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
  {
    id: 3,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
  {
    id: 4,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
  {
    id: 5,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
  {
    id: 6,
    partner_id: "HSTPAY001",
    orderNo: makeid(10),
    amount: 260000,
    token_receive: 10,
    buyer_id: "qer7WGsIdSk6wlTBgvb1CIrp5P02TU",
    hsPay_status: "processcing",
    creater_at: new Date().toISOString(),
    update_at: new Date().toISOString(),
    cvpay_status: "waiting",
    cvpay_create_at: new Date().toISOString(),
    cvpay_update_at: new Date().toISOString(),
  },
];
